SCREEN_WIDTH = 700
SCREEN_HEIGHT = 900

BACKGROUND_COLOR = "DarkBlue"
TITLE = "BreakOut"

# constants.py
PADDLE_COLOR = "White"
PADDLE_STRETCH_WIDTH = 6
PADDLE_STRETCH_HEIGHT = 1
PADDLE_BOTTOM_MARGIN = 30
PADDLE_MOVEMENT_DISTANCE = 20