SCREEN_WIDTH = 650
SCREEN_HEIGHT = 900

BACKGROUND_COLOR = "DarkBlue"
TITLE = "BreakOut"

# main.py
LEFT_BTN = "Left"
RIGHT_BTN = "Right"
BALL_LAUNCH_BTN = "space"

# ui Constants
SCOREBOARD_Y = SCREEN_HEIGHT / 2 - 20
UI_FONT_FAMILY = "Press Start 2P"
SCOREBOARD_FONT = (UI_FONT_FAMILY, 11, "bold")
SCOREBOARD_COLOR = "white"
BUTTON_COLOR = "cyan"
BUTTON_TEXT_COLOR = "black"
BUTTON_FONT = (UI_FONT_FAMILY, 13, "bold")
BUTTON_STRETCH_WIDTH = 6
BUTTON_STRETCH_HEIGHT = 1.5

# game.py
STARTING_LIVES = 3

# constants.py
PADDLE_COLOR = "White"
PADDLE_STRETCH_WIDTH = 6
PADDLE_STRETCH_HEIGHT = 1
PADDLE_BOTTOM_MARGIN = 30
PADDLE_MOVEMENT_DISTANCE = 20
PADDLE_WALL_MARGIN = 30

# ball.py
BALL_COLOR = "Red"
BALL_RADIUS = 10
BALL_BOTTOM_MARGIN = 45
BALL_MOVEMENT_DISTANCE = 10
BALL_PADDLE_COLLISION_MARGIN = -(BALL_BOTTOM_MARGIN - PADDLE_BOTTOM_MARGIN - 20)

# borders
RIGHT_BORDER = SCREEN_WIDTH / 2 - 10
LEFT_BORDER = -SCREEN_WIDTH / 2 + 10
TOP_BORDER = SCREEN_HEIGHT / 2 - 10
BOTTOM_BORDER = -SCREEN_HEIGHT / 2 + 10

# brick.py
BRICK_STRETCH_WIDTH = 3
BRICK_STRETCH_HEIGHT = 1
BRICK_COLORS = [
    "red",
    "orangered",
    "orange",
    "gold",
    "yellow",
    "chartreuse",
    "lime",
    "springgreen",
    "cyan",
    "deepskyblue",
    "dodgerblue",
    "magenta",
    "hotpink",
    "violet",
]

# level.py
DIFFICULTY_STEPUP = 5
BRICK_ROWS = 3
BRICKS_PER_ROW = 9
BRICK_GAP = 10
BRICK_START_Y = SCREEN_HEIGHT // 2 - 40
BRICK_START_X = -(SCREEN_WIDTH // 2) + 40
BRICK_WIDTH = BRICK_STRETCH_WIDTH * 20
BRICK_HEIGHT = BRICK_STRETCH_HEIGHT * 20

# scoreboard.py
BRICK_SCORE = 10
BALL_LOST_PENALTY = 5
LEVEL_SCORE_MULTIPLIER = 100

HIGH_SCORE_FILE = "highscore.txt"
